### ISSUE TITLE
Feature: Image Upload

### ISSUE THREAD

**Issue by Hitscotty** [HecticHiccups/Romanova#1]
## Upload to Background
We need an optional image upload button like the one we had before, but have it right below our current button. The Images need to appear in the background or some where so its clearer to the user what is going on and what the text is about. @A-Beltran @HecticHiccups @soconnor129   

**would be nice to have:**  <br>
semi-transparent background <br>
Hamburger Menu

**Comment by HecticHiccups** [comment]
http://www.w3schools.com/howto/tryhow_css_parallax_demo.htm
Is this what you had in mind?
This is strictly functional on desktop not mobile. @Hitscotty

**Comment by Hitscotty** [comment]
Without the scrolling I guess
